#!/bin/bash
# Simple script to create a new shell script from a template and open it in Vim.

if [ ! -f $1 ]
then
    touch $1
    chmod +x $1
    echo '#!/bin/bash' >> $1
    vim $1
else
    echo File $1 already exists! 
fi
