#!/bin/bash

function coloredEcho(){
    local exp=$1;
    local color=$2;
    if ! [[ $color =~ '^[0-9]$' ]] ; then
       case $(echo $color | tr '[:upper:]' '[:lower:]') in
        black) color=0 ;;
        red) color=1 ;;
        green) color=2 ;;
        yellow) color=3 ;;
        blue) color=4 ;;
        magenta) color=5 ;;
        cyan) color=6 ;;
        white|*) color=7 ;; # white or invalid color
       esac
    fi
    tput setaf $color;
    echo $exp;
    tput sgr0;
}

coloredEcho "Waiting for internet connection..."
itest=$(fping google.com | grep alive)


while [ "$itest" == "" ] 
        do
        sleep 5
        itest=$(fping google.com | grep alive)
done
coloredEcho "Internet connection found! Proceeding with update..." cyan

coloredEcho "Updating package lists..." cyan
sudo apt-get update
coloredEcho "Checking for upgrades..." cyan
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
coloredEcho "Cleaning up..." cyan
sudo apt-get autoremove -y
sudo apt-get clean
coloredEcho "Done!" red
